// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgufxtpqbcjoyadqcxzg.supabase.co";
// Publishable (anon) key — safe to ship in the frontend.
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_UxmT0sDKlErW4gsieJbOaQ_0qkY2w5J";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
