// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amjjmrndrdygcgdxripl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtamptcm5kcmR5Z2NnZHhyaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTA5NTMsImV4cCI6MjA1OTc4Njk1M30.gs_9kHhVCLF-qurP0q1scpGYX2uDQJIhn3X4ZBTcYJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);